### PR TITLE
Update names, remove dead link

### PR DESCRIPTION
**Pull request by adamnfish**
"Big Brother" doesn't work anymore and Lizzy -> Sid for now.

### CODE REVIEW

**Comment by philmcmahon** [comment]
:+1:

**Comment by hoyla** [comment]
What's wrong with big brother? I use it every day, as do many

On 9 May 2016 at 11:32, Adam Fisher notifications@github.com wrote:

> ## "Big Brother" doesn't work anymore and Lizzy -> Sid for now.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/guardian/useful-links/pull/12
> Commit Summary
> - Update names, remove dead link
> 
> File Changes
> - _M_ after-starting.md
>   https://github.com/guardian/useful-links/pull/12/files#diff-0 (3)
> 
> Patch Links:
> - https://github.com/guardian/useful-links/pull/12.patch
> - https://github.com/guardian/useful-links/pull/12.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/guardian/useful-links/pull/12

## 

Luke Hoyland
Guardian News & Media
http://tinyurl.com/contactluke
PGP public key
https://pgp.theguardian.com/PublicKeys/Luke%20Hoyland.pub.txt

## 

---

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by adamnfish** [comment]
@hoyla what URL do you use? The one in the document doesn't work so I thought it was dead...

**Comment by hoyla** [comment]
I use http://octhelp/inventory/bigbrother, which is what you have. Maybe
this is a digidev bubble thing?

L

On 10 May 2016 at 10:17, Adam Fisher notifications@github.com wrote:

> @hoyla https://github.com/hoyla what URL do you use? The one in the
> document doesn't work so I thought it was dead...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/guardian/useful-links/pull/12#issuecomment-218103068

## 

Luke Hoyland
Guardian News & Media
http://tinyurl.com/contactluke
PGP public key
https://pgp.theguardian.com/PublicKeys/Luke%20Hoyland.pub.txt

## 

---

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
