### PR TITLE
Update Teamcity/RiffRaff links

### PR DESCRIPTION
**Pull request by philwills**

### CODE REVIEW

**Comment by rrees** [comment]
@philwills is TeamCity back on the non-AWS link now?

**Comment by philwills** [comment]
It's not. It probably should be, but it's a bit of a faff, as the way Teamcity works means that you can't have two DNS addresses working properly simultaneously and so switch overs effectively require a little down time. I haven't yet summoned the will power to go through that.

**Comment by philmcmahon** [comment]
Rebased against master and added circle ci link

**Comment by rrees** [comment]
👍

**Pull request merged**
